<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Work Order Management</name>
   <tag></tag>
   <elementGuidId>ea1cdbf5-f8e6-405a-8574-4d3a2153de93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b7-Content']/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.heading5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b80cf5b-8e02-479f-8969-a8b278b495ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading5</value>
      <webElementGuid>4c04eb21-b42c-4c2e-a1b1-d0f575f75444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work Order Management</value>
      <webElementGuid>bc69bacb-9891-465e-9aea-025bbe99b4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-Content&quot;)/div[@class=&quot;card-detail-center&quot;]/span[@class=&quot;heading5&quot;]</value>
      <webElementGuid>78d05495-d295-4868-b444-5c74c08cd26d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-Content']/div[2]/span</value>
      <webElementGuid>9c9ff379-3e3a-405f-8859-106070e543f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moxie'])[1]/following::span[1]</value>
      <webElementGuid>d1ca7bc2-1957-4a45-8118-8aaa598c96c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K3 Core Platform'])[1]/following::span[2]</value>
      <webElementGuid>1c967649-4802-4266-82f0-2eb7a1b84f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduler'])[1]/preceding::span[1]</value>
      <webElementGuid>762d67e6-2b93-4b74-b9ec-5a6dc9937823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BDM Dashboard'])[1]/preceding::span[2]</value>
      <webElementGuid>3d92cd09-d953-4986-92b7-074e838be3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Work Order Management']/parent::*</value>
      <webElementGuid>2961414c-09c2-4e27-8b18-017b0a3e9a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>f479aa83-69b9-49f6-8831-3055e7338d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Work Order Management' or . = 'Work Order Management')]</value>
      <webElementGuid>31e5a896-33bd-4a84-a43c-38d4af479b09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
