<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Work Order Management</name>
   <tag></tag>
   <elementGuidId>ea1cdbf5-f8e6-405a-8574-4d3a2153de93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b7-Content']/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.heading5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6eeeeaf7-bd88-416c-a795-59961bb815f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading5</value>
      <webElementGuid>cca90215-06ec-4dfe-a1bc-8c15047dafe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work Order Management</value>
      <webElementGuid>ea491b0d-3537-419f-abd5-bb7b2a390fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-Content&quot;)/div[@class=&quot;card-detail-center&quot;]/span[@class=&quot;heading5&quot;]</value>
      <webElementGuid>cf4f2295-2e10-41ff-886e-9927d66240fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-Content']/div[2]/span</value>
      <webElementGuid>2dc9b8fe-bd5e-4438-b0cf-fabb562c69bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moxie'])[1]/following::span[1]</value>
      <webElementGuid>90550ade-5694-4f9d-b091-5813a3310395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K3 Core Platform'])[1]/following::span[2]</value>
      <webElementGuid>18bcd617-dcfb-4152-ae5f-f65da114a1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduler'])[1]/preceding::span[1]</value>
      <webElementGuid>60bf5407-2bfe-463a-a5a9-372a4e12ee90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BDM Dashboard'])[1]/preceding::span[2]</value>
      <webElementGuid>196de479-740d-4096-989b-cfae64fecdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Work Order Management']/parent::*</value>
      <webElementGuid>afc8779e-b922-4f47-bbc8-db7cbcfe43fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>5c9c8d4e-456f-4f35-a59a-255ea309f402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Work Order Management' or . = 'Work Order Management')]</value>
      <webElementGuid>320aa8b0-5d54-4908-8d7d-43440f96e0a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
