<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Input_PasswordVal</name>
   <tag></tag>
   <elementGuidId>1581a87d-cbfe-4ec8-9df4-400f4f0a4b3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_PasswordVal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Input_PasswordVal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d3ec2c9-5f01-4ec4-8771-1dbf3845d5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control login-password text-neutral-0 OSFillParent</value>
      <webElementGuid>caa8fa14-4d71-4049-8a3a-e1e6b64f6f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4d1d1d6e-4a73-4f0c-9a26-332ca2e119b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b7903878-ef41-4072-8a95-c7e80ad7e62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_PasswordVal</value>
      <webElementGuid>90cdec27-3736-45cb-9e9f-d6acdbdb3cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_PasswordVal&quot;)</value>
      <webElementGuid>f59e60c8-ac1d-4a9f-ae8a-fafc7a7814ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_PasswordVal']</value>
      <webElementGuid>0dfb3ea0-9e81-415a-b68f-f5bf9b5276bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-Input']/span/input</value>
      <webElementGuid>10003377-d480-4c67-a52c-58930afed8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/input</value>
      <webElementGuid>24ea9a9b-ff28-431e-b96c-1feaabe645e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'Input_PasswordVal']</value>
      <webElementGuid>da86959d-1cfb-4d91-bc63-2948504b15d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
